### ISSUE TITLE
Rendering error in bike share example with server-side webpack

### ISSUE THREAD

**Issue by karlhorky** [karlhorky/react-server-bike-share-example#1]
[kununu/create-universal-react-app](https://github.com/kununu/create-universal-react-app) depends on the [jhnns/react-server](https://github.com/jhnns/react-server) and [jhnns/react-server-cli](https://github.com/jhnns/react-server-cli) repos, which are in turn based off of @drewpc's redfin/react-server#791.

These repos, when used as dependencies in the new Express Bike Share example introduced by @jhnns in redfin/react-server#825, throws a rendering error in `react-server.core.renderMiddleware` (`Error rendering element 1 message=res.expose is not a function, stack=TypeError: res.expose is not a function`).

Full stack trace:

```js
2017-02-14T16:32:35.639Z - info: [bike-share.components.network-card] rendering card for network RiviBike
2017-02-14T16:32:35.639Z - info: [bike-share.components.network-card] rendering card for network Bilbon Bizi
2017-02-14T16:32:35.640Z - info: [bike-share.components.network-card] rendering card for network Relay Bike Share
2017-02-14T16:32:35.654Z - slow: [react-server.core.renderMiddleware] renderElement.individual.NetworkList ms=685
2017-02-14T16:32:35.655Z - slow: [react-server.core.renderMiddleware] renderElement.fromStart.NetworkList ms=2359
2017-02-14T16:32:35.660Z - debug: [react-server.core.util.PageUtil] Call getJsBelowTheFold
2017-02-14T16:32:35.693Z - error: [react-server.core.renderMiddleware] Error rendering element 1 message=res.expose is not a function, stack=TypeError: res.expose is not a function
    at bootstrapClient (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/react-server/target/server/renderMiddleware.js:937:6)
    at writeElement (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/react-server/target/server/renderMiddleware.js:903:3)
    at writeElements (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/react-server/target/server/renderMiddleware.js:858:3)
    at doElement (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/react-server/target/server/renderMiddleware.js:677:3)
    at /Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/react-server/target/server/renderMiddleware.js:684:20
    at /Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/continuation-local-storage/context.js:84:17
    at _fulfilled (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/q/q.js:796:13)
    at /Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/q/q.js:604:44
    at runSingle (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/q/q.js:137:13)
    at flush (/Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/q/q.js:125:13)
    at /Users/karlhorky/projects/react-server/packages/react-server-examples/bike-share/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
2017-02-14T16:32:35.696Z - slow: [react-server.core.renderMiddleware] lifecycle.individual.writeBody ms=1985
2017-02-14T16:32:35.696Z - slow: [react-server.core.renderMiddleware] lifecycle.fromStart.writeBody ms=2401
2017-02-14T16:32:35.696Z - fast: [react-server.core.renderMiddleware] lifecycle.individual.wrapUpLateArrivals ms=0
2017-02-14T16:32:35.696Z - slow: [react-server.core.renderMiddleware] lifecycle.fromStart.wrapUpLateArrivals ms=2401
2017-02-14T16:32:35.701Z - fast: [react-server.core.renderMiddleware] lifecycle.individual.closeBody ms=5
2017-02-14T16:32:35.701Z - slow: [react-server.core.renderMiddleware] lifecycle.fromStart.closeBody ms=2406
2017-02-14T16:32:35.701Z - fast: [react-server.core.renderMiddleware] lifecycle.individual.handleResponseComplete ms=0
2017-02-14T16:32:35.702Z - slow: [react-server.core.renderMiddleware] lifecycle.fromStart.handleResponseComplete ms=2407
2017-02-14T16:32:35.705Z - fast: [react-server.core.renderMiddleware] lifecycle.individual.endResponse ms=4
2017-02-14T16:32:35.705Z - slow: [react-server.core.renderMiddleware] lifecycle.fromStart.endResponse ms=2410
2017-02-14T16:32:35.799Z - ok: [react-server.core.renderMiddleware] countDataRequests val=1
2017-02-14T16:32:35.802Z - ok: [react-server.core.renderMiddleware] countLateArrivals val=0
2017-02-14T16:32:35.802Z - ok: [react-server.core.renderMiddleware] bytesRead val=467
2017-02-14T16:32:35.802Z - ok: [react-server.core.renderMiddleware] bytesWritten val=205876
2017-02-14T16:32:35.802Z - slow: [react-server.core.renderMiddleware] responseCode.200 ms=2507
2017-02-14T16:32:35.802Z - slow: [react-server.core.renderMiddleware] totalRequestTime ms=2507
2017-02-14T16:32:35.802Z - slow: [react-server.core.renderMiddleware] totalRenderTime ms=748
2017-02-14T16:32:35.802Z - debug: [react-server.core.util.PageUtil] Call handleComplete
```

**Comment by karlhorky** [comment]
This should apparently be fixed by https://github.com/jhnns/react-server-cli/commit/fb4c0664766023221a0d3523f1613b8e2756d1d7

**Comment by karlhorky** [comment]
Will test and close after #2 is fixed
